on:
  push:
    branches:
      - staging # Hanya berjalan untuk push ke branch staging

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🛠️ Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Sesuaikan versi PHP dengan kebutuhan
          extensions: mbstring, intl, xml, pdo, pdo_pgsql # Tambahkan pdo_pgsql untuk PostgreSQL
          coverage: none

      - name: 🔧 Set up PostgreSQL database
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: 🧩 Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-ansi --no-interaction --optimize-autoloader

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 103.109.210.53
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
